name: smartedu_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.11.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.4.3
  google_sign_in: ^6.2.1

  equatable: ^2.0.8
  flutter_tts: ^4.2.2
  just_audio: ^0.9.42
  intl: ^0.19.0
  http: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  image_picker: ^1.2.2
  
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true