// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF2CS_E7pScZwzVt-4qTaxui5ud5k9-EU',
    appId: '1:681946323599:web:0027f5ffa517accde66efa',
    messagingSenderId: '681946323599',
    projectId: 'smartedu-hub-b5459',
    authDomain: 'smartedu-hub-b5459.firebaseapp.com',
    storageBucket: 'smartedu-hub-b5459.firebasestorage.app',
    measurementId: 'G-H3PGJ1M4M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJN_U9O-H8sf4-ADTDB0IuHO7JCfJTG8',
    appId: '1:681946323599:android:ad6250d6307ea7c7e66efa',
    messagingSenderId: '681946323599',
    projectId: 'smartedu-hub-b5459',
    storageBucket: 'smartedu-hub-b5459.firebasestorage.app',
  );
}
